#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <time.h>
#include <stdbool.h>

#define MAX_LENGTH 25

struct employee
{
   char fname[MAX_LENGTH];
   char lname[MAX_LENGTH];
   int empId;              // this is auto-generated by the program
   int numDependents;
   char  ** dependents;    // this array is dynamically allocated
   struct employee * nextEmployee;   //pointer to next employee   
};
typedef struct employee a3Emp;

//dependencies
void loadEmpData (struct employee ** headLL, char fileName [MAX_LENGTH]); //loads the employees
a3Emp *createEmpDataFromFile(FILE *filePtr);
//Menu Choices
void recruitEmployee (struct employee ** headLL); //add a new employee (1)
void printAll (struct employee * headLL); //print data of all employees (2)
void printOne (struct employee * headLL, int whichOne); //print one employee (3)
int lookOnId (struct employee * headLL, int whichEmpId); //search based on ID (4)
int lookOnFullName (struct employee * headLL, char whichName [100]); //search based on full name (5)
int countEmployees (a3Emp * headLL); //Counts the total number of employees (6)
void sortEmployeesId (struct employee * headLL); //sort based on ID (7)
void fireOne (a3Emp ** headLL, int whichOne); //remove one employee (8)
void fireAll (a3Emp ** headLL); //Remove all employees (9)


